# Site
name: "Pijamas Beauty"
title: "Pijamas Beauty"
description: "All Fashion Dog Style trends of this year and best clothes for your Dog pet! See more ideas about dog clothes, love pet, trending fashion outfits. You love pets or you are a dog owner? All trends of this year and best clothes for your pet! Follow us!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 'https://khuynhtroc.github.io/pijamas.beauty'
google_analytics: 'UA-237007012-1'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: huynhnt135@gmail.com

# Authors
authors:
  darius:
    name: Darius
    display_name: Darius
    avatar: 'assets/images/avatar-sal.png'
    email: huynhnt135@gmail.com
    web: 
    twitter: https://twitter.com/huynhtroc
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 100
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
